name: Upload to Google Drive and Start App

on:
  push:
    branches: [main]
  workflow_dispatch:           # ✅ Manual trigger support
  schedule:
    - cron: '30 4 * * *'       # ✅ Daily at 4:30 AM UTC (change if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Create test file (for upload)
        run: |
          mkdir -p to-upload
          echo "Uploaded at $(date)" > to-upload/example.txt

      - name: Upload to Google Drive
        run: |
          rclone copy to-upload gdrive:/GitHubUploads --drive-chunk-size=64M -v

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Node.js dependencies
        run: npm install

      - name: Start application with PM2
        run: |
          npm install -g pm2
          pm2 start sula.js --deep-monitoring --attach --name SulaMd
